
XDG_CONFIG_HOME DEFAULT=@{HOME}/.config
XDG_DATA_HOME DEFAULT=@{HOME}/.sys/data
XDG_CACHE_HOME DEFAULT=@{HOME}/.sys/cache
XDG_STATE_HOME DEFAULT=@{HOME}/.sys/state

UENV_USR_SPEC DEFAULT=dotsys
UENV_USR_SYS DEFAULT=@{HOME}/.sys
UENV_USR_CONFIG DEFAULT=@{HOME}/.config
UENV_USR_DATA DEFAULT=@{HOME}/.sys/data
UENV_USR_CACHE DEFAULT=@{HOME}/.sys/cache
UENV_USR_STATE DEFAULT=@{HOME}/.sys/state
UENV_USR_SUBSYS DEFAULT=@{HOME}/.sys/of
UENV_USR_LOCAL DEFAULT=@{HOME}/.sys/local
UENV_USR_ADHOC DEFAULT=@{HOME}/.sys/adhoc
UENV_USR_MOUNT DEFAULT=@{HOME}/.sys/mnt
UENV_USR_PATHS DEFAULT=@{HOME}/.sys/paths
UENV_USR_SERVE DEFAULT=@{HOME}/.sys/srv
UENV_USR_SYNC DEFAULT=@{HOME}/.sys/sync
UENV_USR_SECRET DEFAULT=@{HOME}/.sys/secret
UENV_USR_SECRET_MOUNT DEFAULT=@{HOME}/.sys/mnt/secret
